//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_GehirnJogging
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventar
    {
        public int ID { get; set; }
        public int ItemID { get; set; }
        public int CharakterID { get; set; }
    
        public virtual Charakter Charakter { get; set; }
        public virtual Item Item { get; set; }
    }
}
