//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_GehirnJogging
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GehirnjoggingEntities : DbContext
    {
        public GehirnjoggingEntities()
            : base("name=GehirnjoggingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Charakter> Charakters { get; set; }
        public virtual DbSet<Enemy> Enemies { get; set; }
        public virtual DbSet<Inventar> Inventars { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Levelinfo> Levelinfos { get; set; }
        public virtual DbSet<Level> Levels { get; set; }
        public virtual DbSet<PassedLevel> PassedLevels { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Savegame> Savegames { get; set; }
        public virtual DbSet<Type> Types { get; set; }
    }
}
