//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_GehirnJogging
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassedLevel
    {
        public int ID { get; set; }
        public int SavegameID { get; set; }
        public string Time { get; set; }
        public int LevelID { get; set; }
    
        public virtual Level Level { get; set; }
        public virtual Savegame Savegame { get; set; }
    }
}
